const itemList = [
    // {id:'1',title:'가슴뛰는 스포츠 레전드',header:true},
    // {id:'1.1',title:'641',img:require('../assets/img/641.jpg'),header:false},
    // {id:'1.2',title:'642',img:require('../assets/img/642.jpg'),header:false},
    // {id:'1.3',title:'643',img:require('../assets/img/643.jpg'),header:false},
    // {id:'1.4',title:'644',img:require('../assets/img/644.jpg'),header:false},
    // {id:'1.5',title:'645',img:require('../assets/img/645.jpg'),header:false},
    // {id:'1.6',title:'646',img:require('../assets/img/646.jpg'),header:false},
    // {id:'2',title:'입꼬리 주의 개그 레전드',header:true},
    // {id:'3',title:'순수한 액션을 원한다면',header:true},
    // {id:'4',title:'감성충만 힐링웨툰',header:true},
    // {id:'5',title:'동면주인 연애세포를 깨워보자',header:true},
    // {id:'6',title:'이번주 신작',header:true}
    {title:'가슴뛰는 스포츠 레전드',data:[[{name:'641',img:require('../assets/img/641.jpg')},
                                        {name:'642',img:require('../assets/img/642.jpg')},
                                        {name:'643',img:require('../assets/img/643.jpg')},
                                        {name:'644',img:require('../assets/img/644.jpg')},                         
                                        {name:'645',img:require('../assets/img/645.jpg')},
                                        {name:'126',img:require('../assets/img/126.jpg')},                         
                                        {name:'127',img:require('../assets/img/127.jpg')},
                                        {name:'646',img:require('../assets/img/646.jpg')}
    ]]},
    {title:'입꼬리 주의 개그 레전드',data:[[{name:'641',img:require('../assets/img/641.jpg')},
    {name:'642',img:require('../assets/img/642.jpg')},
    {name:'643',img:require('../assets/img/643.jpg')},
    {name:'644',img:require('../assets/img/644.jpg')},                         
    {name:'645',img:require('../assets/img/645.jpg')},
    {name:'126',img:require('../assets/img/126.jpg')},                         
    {name:'127',img:require('../assets/img/127.jpg')},
    {name:'646',img:require('../assets/img/646.jpg')}
    ]]},
    {title:'순수한 액션을 원한다면',data:[[{name:'641',img:require('../assets/img/641.jpg')},
    {name:'642',img:require('../assets/img/642.jpg')},
    {name:'643',img:require('../assets/img/643.jpg')},
    {name:'644',img:require('../assets/img/644.jpg')},                         
    {name:'645',img:require('../assets/img/645.jpg')},
    {name:'126',img:require('../assets/img/126.jpg')},                         
    {name:'127',img:require('../assets/img/127.jpg')},
    {name:'646',img:require('../assets/img/646.jpg')}
    ]]},
    {title:'감성충만 힐링웨툰',data:[[{name:'641',img:require('../assets/img/641.jpg')},
    {name:'642',img:require('../assets/img/642.jpg')},
    {name:'643',img:require('../assets/img/643.jpg')},
    {name:'644',img:require('../assets/img/644.jpg')},                         
    {name:'645',img:require('../assets/img/645.jpg')},
    {name:'126',img:require('../assets/img/126.jpg')},                         
    {name:'127',img:require('../assets/img/127.jpg')},
    {name:'646',img:require('../assets/img/646.jpg')}
]]},
    {title:'동면주인 연애세포를 깨워보자',data:[[{name:'641',img:require('../assets/img/641.jpg')},
    {name:'642',img:require('../assets/img/642.jpg')},
    {name:'643',img:require('../assets/img/643.jpg')},
    {name:'644',img:require('../assets/img/644.jpg')},                         
    {name:'645',img:require('../assets/img/645.jpg')},
    {name:'126',img:require('../assets/img/126.jpg')},                         
    {name:'127',img:require('../assets/img/127.jpg')},
    {name:'646',img:require('../assets/img/646.jpg')}
]]},
    {title:'이번주 신작',data:[[{name:'641',img:require('../assets/img/641.jpg')},
    {name:'642',img:require('../assets/img/642.jpg')},
    {name:'643',img:require('../assets/img/643.jpg')},
    {name:'644',img:require('../assets/img/644.jpg')},                         
    {name:'645',img:require('../assets/img/645.jpg')},
    {name:'126',img:require('../assets/img/126.jpg')},                         
    {name:'127',img:require('../assets/img/127.jpg')},
    {name:'646',img:require('../assets/img/646.jpg')}
]]}
];